### PR TITLE
Adding `openghg --quickstart` command line options

### LINKED ISSUE #503: Add more information about the creation of the config file to Quickstart

### LINKED ISSUE #505: Update installation instructions
### Feature that's missing

Not a missing feature - Update instructions to state that you must import openghg for it to install the config file ~/.config/openghg/openghg.conf

### Describe the solution you'd like

Change:

OpenGHG should now be installed, you can check this by opening ipython and running

To: OpenGHG should now be installed and you need to import this once to generate the file ~/.config/openghg/openghg.conf

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### Additional code / helper functions

_No response_

### LINKED ISSUE #520: Add user quickstart
Add a quickstart command line interface to allow easier creation of the config file, updating it etc.

### PR DESCRIPTION
**Pull request by gareth-j**
This adds the ability to run `openghg-quickstart` on the command line. This then guides the user through the process of creating the configuration file.

Should close #520 
Closes #503 
Closes #505

### CODE REVIEW

**Comment by gareth-j** [comment]
This should close #520

**Comment by rt17603** [comment]
@gareth-j - Shall I wait until the tests have been updated to review this PR?

**Comment by gareth-j** [comment]
> @gareth-j - Shall I wait until the tests have been updated to review this PR?

Yeah, I've decided to make some more changes to make the command line interface a lot cleaner and simpler. I'll let you know once it's ready for review.

**Comment by gareth-j** [comment]
I think most of the code is there now, just need to update the documentation and this should be done.

**Comment by rt17603** [comment]
I ran through the steps for setting up using the "pip" instructions from https://github.com/openghg/openghg/blob/c2d3692ff6d855a55e9d5d83e907d6881e020b22/doc/source/development/quickstart_devel.rst. Last command run was `$ pip install -e .`

At the `openghg --quickstart` step I get the following message about this not being recognised:
```
(openghg_devel) rt17603@IT072382:~/test/openghg> openghg --quickstart
If 'openghg' is not a typo you can use command-not-found to lookup the package that contains it, like this:
    cnf openghg
```

I'm running on WSL2, OpenSUSE Leap 15.3 so a Linux environment. Is there a step missing here or something that works differently on different systems?

**Comment by rt17603** [comment]
> I ran through the steps for setting up using the "pip" instructions from https://github.com/openghg/openghg/blob/c2d3692ff6d855a55e9d5d83e907d6881e020b22/doc/source/development/quickstart_devel.rst. Last command run was `$ pip install -e .`
> 
> At the `openghg --quickstart` step I get the following message about this not being recognised:
> 
> ```
> (openghg_devel) rt17603@IT072382:~/test/openghg> openghg --quickstart
> If 'openghg' is not a typo you can use command-not-found to lookup the package that contains it, like this:
>     cnf openghg
> ```
> 
> I'm running on WSL2, OpenSUSE Leap 15.3 so a Linux environment. Is there a step missing here or something that works differently on different systems?

This can be ignored - I've now managed to get this to work.

**Review by rt17603 — APPROVED** [review]
This all looks good to me.

I checked this could run within WSL (OpenSUSE Leap 15.3) and this detected the object store and gave a helpful message.

**Comment by rt17603** [comment]
This test `tests/retrieve/icos/test_retrieve_icos.py::test_icos_retrieve_and_store` fails for me locally. Looks like the same is happening the CI as well.
```
...
assert first_expected_metadata.items() <= first_obs_metadata.items()
E       AssertionError: assert dict_items([('species', 'co2'), ('instrument', 'ftir'), ('site', 'wao'),
...
```

**Pull request merged**
