### PR TITLE
Added store argument to search

### LINKED ISSUE #754: data_manager not selecting by store
### What happened?

Apologies if this is being fixed elsewhere, but I noticed that when running store.data_manager it returns results from all the stores in my openghg.conf file, not just the one specified in the call to store.data_manager. I've attached my openghg.conf file.
[openghg.conf.txt](https://github.com/openghg/openghg/files/12361303/openghg.conf.txt)

### What did you expect to happen?

I expect the example below to return nothing, because I don't have any CH4 data in my personal store. If I remove the reference to Alice's Paris store from my openghg.conf, it does indeed return nothing. However, if Alice's Paris store is in my openghg.conf, the example below returns the matching entries in her store, despite the fact that I have specified store="user"

### Minimal Complete Verifiable Example

```Python
decc_dm = store.data_manager(network="decc",
                             species="ch4",
                             data_type="surface",
                             store="user")
uuids = list(decc_dm.metadata.keys())
decc_dm.metadata
```

### Relevant log output

```Python
{'928046c8-448e-4163-a38f-b28dc2fc05ed': {'data_type': 'surface',
  'site': 'rgl',
  'species': 'ch4',
  'network': 'decc',
  'instrument': 'picarro',
  'sampling_period': '60.0',
  'calibration_scale': 'wmo-x2004a',
  'data_owner': "simon o'doherty",
  'data_owner_email': 's.odoherty@bristol.ac.uk',
  'inlet': '90m',
  'inlet_height_magl': '90',
  'station_longitude': -2.53977,
  'station_latitude': 51.99738,
  'station_long_name': 'ridge hill, uk',
  'station_height_masl': '200.0',
  'uuid': '928046c8-448e-4163-a38f-b28dc2fc05ed',
  'start_date': '2012-02-23 16:00:00+00:00',
  'end_date': '2023-08-04 12:16:59+00:00',
  'latest_version': 'v1'},
 '1448f621-cd8a-451a-813d-8608db8b8bf7': {'data_type': 'surface',
  'site': 'hfd',
  'species': 'ch4',
  'network': 'decc',
  'instrument': 'picarro',
  'sampling_period': '60.0',
  'calibration_scale': 'wmo-x2004a',
  'data_owner': 'tim arnold',
  'data_owner_email': 'tim.arnold@npl.co.uk',
  'inlet': '100m',
  'inlet_height_magl': '100',
  'station_longitude': 0.23042,
  'station_latitude': 50.97661,
  'station_long_name': 'heathfield, uk',
  'station_height_masl': '150.0',
  'uuid': '1448f621-cd8a-451a-813d-8608db8b8bf7',
  'start_date': '2014-03-10 12:07:00+00:00',
  'end_date': '2023-08-03 23:54:59+00:00',
  'latest_version': 'v1'},
 '4b9bc89e-d017-406c-84e6-b0e1ac89cee7': {'data_type': 'surface',
  'site': 'bsd',
  'species': 'ch4',
  'network': 'decc',
  'instrument': 'picarro',
  'sampling_period': '60.0',
  'calibration_scale': 'wmo-x2004a',
  'data_owner': "simon o'doherty",
  'data_owner_email': 's.odoherty@bristol.ac.uk',
  'inlet': '248m',
  'inlet_height_magl': '248',
  'station_longitude': -1.15018,
  'station_latitude': 54.35846,
  'station_long_name': 'bilsdale, uk',
  'station_height_masl': '380.0',
  'uuid': '4b9bc89e-d017-406c-84e6-b0e1ac89cee7',
  'start_date': '2014-01-30 10:52:00+00:00',
  'end_date': '2021-08-10 12:14:59+00:00',
  'latest_version': 'v1'}}
```

### Anything else we need to know?

_No response_

### Environment

Using OpenGHG devel branch:
commit 5e6a8d0c1dbcc7635f88daaa7dd5f065b0bc3654 (HEAD -> devel, origin/devel, origin/HEAD)
Merge: bf23c2c00 51e5d7173
Author: Gareth Jones <8915182+gareth-j@users.noreply.github.com>
Date:   Tue Aug 15 11:24:48 2023 +0100

Python 3.10.10

### PR DESCRIPTION
**Pull request by SutarPrasad**
* **Summary of changes** (Bug fix, feature, docs update, ...)

Added store argument to the function search() inside _datamanager.py to show the store-specific results.

* **Please check if the PR fulfills these requirements**

- [x] Closes #754  (Replace xxxx with the Github issue number)
- [x] All code checks passing - `black --line-length 110` run over code, `mypy` and `flake8` not showing any errors

### CODE REVIEW

**Comment by gareth-j** [comment]
Why am I assigned to this?

**Comment by gareth-j** [comment]
Ah sorry, I was worried I'd forgotten a conversation or something!

**Review by gareth-j — APPROVED** [review]
Looks good!

**Comment by SutarPrasad** [comment]
No No, its good that you highlighted that, I must have mistakenly put you in assignee instead of reviewer. Apologies for the confusion.

From: Gareth Jones ***@***.***>
Date: Wednesday, 10 January 2024 at 13:48
To: openghg/openghg ***@***.***>
Cc: Prasad Sutar ***@***.***>, Assign ***@***.***>
Subject: Re: [openghg/openghg] Added store argument to search (PR #859)

Ah sorry, I was worried I'd forgotten a conversation or something!

**Pull request merged**
