### PR TITLE
Add processing of AGAGE NetCDF data and its export to dashboard

### LINKED ISSUE #781: Add standardisation script for processing of new AGAGE NetCDF format
Add a simple standardisation module for adding the new AGAGE NetCDF files to the object store.

### PR DESCRIPTION
**Pull request by gareth-j**
* **Summary of changes** (Bug fix, feature, docs update, ...)

This will add the ability to standardise the new AGAGE NetCDF files and add the data to the object store.

* **Please check if the PR fulfills these requirements**

- [x] Closes #781 
- [x] [Tests added and passed](https://docs.openghg.org/development/python_devel.html#testing) if fixing a bug or adding a new feature
- [x] All code checks passing - `black --line-length 110` run over code, `mypy` and `flake8` not showing any errors
- [ ] Documentation and tutorials updated/added
- [x] Added an entry in the latest `CHANGELOG.md` file if fixing a bug or adding a new feature

### CODE REVIEW

**Comment by brendan-m-murphy** [comment]
While you're working on the compression code, there is a typo in line 620 (on devel) of _datasource.py:

```
                        logger.warning(
                            f"Storing footprint for date range {daterange} without compression due to netCDF4 RuntimeError."
                        )
```

"footprint" should be replaced by the right data type, or something generic.

**Comment by gareth-j** [comment]
> While you're working on the compression code, there is a typo in line 620 (on devel) of _datasource.py:
> 
> ```
> logger.warning(
>     f"Storing footprint for date range {daterange} without compression due to netCDF4 RuntimeError."
> )
> ```
> 
> "footprint" should be replaced by the right data type, or something generic.

Yeah I just updated it in a bit of a hacky way for now so I can process this data. I'll make sure it doesn't fail horribly and then leave it as this will all get replaced by the zarr stuff anyway.

**Comment by gareth-j** [comment]
I'll extract the `to_dashboard` function to `to_dashbard_agage` and open a new PR for this.

**Comment by gareth-j** [comment]
Closing, added the modified export function with #1030.

**Pull request closed without merging**
