### PR TITLE
Make metadata store source of truth for Datasource UUIDs

### LINKED ISSUE #751: Make the metadata store the single source of truth for Datasource UUIDs
@joe-pitt has encountered an error on BP1 where for some reason the dictionary of Datasource UUIDs has been cleared for each of the storage classes. I'm not sure how this has happened but it prevented the removal of data from the object store using the `DataManager`.

I think we should remove the storage of Datasource UUIDs from the base storage class and just read the data in when the class is instantiated.

### PR DESCRIPTION
**Pull request by gareth-j**
* **Summary of changes** (Bug fix, feature, docs update, ...)

This makes the metadata store for each storage class the source of truth for `Datasource` UUIDs. This will prevent synchronisation issues.

* **Please check if the PR fulfills these requirements**

- [x] Closes #751 
- [x] [Tests added and passed](https://docs.openghg.org/development/python_devel.html#testing) if fixing a bug or adding a new feature
- [x] All code checks passing - `black --line-length 110` run over code, `mypy` and `flake8` not showing any errors
- [ ] Documentation and tutorials updated/added
- [x] Added an entry in the latest `CHANGELOG.md` file if fixing a bug or adding a new feature
- [ ] Added any new requirements to `requirements.txt` and `recipes/meta.yaml`

### CODE REVIEW

**Review by brendan-m-murphy — DISMISSED** [review]
Looks good to me!

**Review by brendan-m-murphy — DISMISSED** [review]
I reverted the changes I made previously, since the long running time on ES_store was due to a flux file with 8700 versions.

**Comment by gareth-j** [comment]
It's crazy there were that many versions. We should ask Eric what he was running when that happened. I wonder if the code in issue [#✈️](https://github.com/openghg/openghg/issues/747) could have prevented the creation of that many versions? I think Rachel's new versioning code might help stop issues like that.

**Review by rt17603 — COMMENTED** [review]
Quick question before this gets merged: Are we assuming the "UUID" now is essentially the code/details used to locate the data? In which case there's no point internally storing it associated with the data?

**Comment by brendan-m-murphy** [comment]
> > It's crazy there were that many versions. We should ask Eric what he was running when that happened. I wonder if the code in issue [#✈️](https://github.com/openghg/openghg/issues/747) could have prevented the creation of that many versions? I think Rachel's new versioning code might help stop issues like that.
> 
> Yeah - it would be useful to know what process caused that! In the new versioning it would raise an Error the second time it tried to add so harder to do by accident (but it would be possible with the correct flags).

I think what was happening was that some of the files being uploaded were for very short time frames, so a month of data required over 100 calls to standardise_flux. I was just poking around in ipython on BP1, I could get the details again if you like.

I think something we'll need to deal with is adding data in smaller amounts than our chunk sizes. These shouldn't be "revisions" if the new data doesn't overlap the old data. So we need to check something more specific than "this new data's time period overlaps with the chunk time period".

**Comment by rt17603** [comment]
> I think something we'll need to deal with is adding data in smaller amounts than our chunk sizes. These shouldn't be "revisions" if the new data doesn't overlap the old data. So we need to check something more specific than "this new data's time period overlaps with the chunk time period".

It sounds like this is what has already been implemented in PR #653 which is currently on the `new_object_store` parallel branch - see also Issue #591

**Comment by brendan-m-murphy** [comment]
> Quick question before this gets merged: Are we assuming the "UUID" now is essentially the ID used to locate the data? In which case there's no point internally storing it in a place associated with the data but better to only store it in a central location as a reference (i.e. the metastore)?

As in, the datasources don't need to save their UUID? Some of the datasource metadata was useful in figuring out what happened with the 8000 versions. So some kind of logging for datasources is useful, but maybe not the UUID and bucket, since you need to know those to load the Datasource.

**Comment by rt17603** [comment]
> As in, the datasources don't need to save their UUID?

Yes - that seems like the purpose for this PR if I'm understanding the summary - the Datasource no longer internally stores it's UUID but I'm just checking that doesn't matter as the UUID is how the Datasource is retrieved anyway. Just ensuring I understand the logic being included here.

**Comment by brendan-m-murphy** [comment]
> > I think something we'll need to deal with is adding data in smaller amounts than our chunk sizes. These shouldn't be "revisions" if the new data doesn't overlap the old data. So we need to check something more specific than "this new data's time period overlaps with the chunk time period".
> 
> It sounds like this is what has already been implemented in PR #653 which is currently on the `new_object_store` parallel branch - see also Issue #591

In lines 190-197 in _datasource.py in PR #653: if there are duplicate times, this should force a new version/revision, or raise an error if the person adding the data hasn't indicated that they are revising data (or maybe have an option that allows adding but not overwriting... so the new duplicates are dropped).

Also, if you do line 197 no matter what, you don't need line 190. (Not sure it's much of a performance gain...)

As it is, I think the code in PR #653 means that you must overwrite if the new data date range overlaps with the date range of an existing chunk. I think the default should be, allow this without overwrite as long as there are no duplicate timestamps. If there are duplicate time stamps, then either the revision number must increase, or the new timestamps should be dropped (although maybe just an error would be better...)

**Comment by brendan-m-murphy** [comment]
...it's possible that I missed something in how the date ranges are represented in the existing data, so that the "overlapping date range" scenario only happens if you are trying to modify existing data. But I don't think that's how it works in v6.2 at least.

**Comment by rt17603** [comment]
> The Datasources still know their own UUID as it's part of the JSON they save/load themselves from. This just stops the storing of the Datasource UUIDs in the storage classes themselves. Datasource UUIDs are now just stored in the metadata store.

Ok understood - thanks for clarifying.

**Comment by rt17603** [comment]
> In lines 190-197 in _datasource.py in PR #653: if there are duplicate times, this should force a new version/revision, or raise an error if the person adding the data hasn't indicated that they are revising data (or maybe have an option that allows adding but not overwriting... so the new duplicates are dropped).

Yes that's what it's doing.

> Also, if you do line 197 no matter what, you don't need line 190. (Not sure it's much of a performance gain...)

Details around checking the overlaps is being changed - work in progress (see #591 for intent here)

> As it is, I think the code in PR #653 means that you must overwrite if the new data date range overlaps with the date range of an existing chunk. I think the default should be, allow this without overwrite as long as there are no duplicate timestamps. If there are duplicate time stamps, then either the revision number must increase, or the new timestamps should be dropped (although maybe just an error would be better...)

We would want to carefully consider whether we should be collating data in this way (especially without proper signalling from the user). Adding data before the start or after the end is relatively safe but collating data could fundamentally change the data timeseries included.

**Comment by brendan-m-murphy** [comment]
> Yes this isn't in the current devel or master version yet as it's sitting on the parallel [`new_object_store` branch](https://github.com/openghg/openghg/tree/new_object_store) - this is part of the ["Special Release" milestone](https://github.com/openghg/openghg/milestone/13).

It seems that `get_representative_daterange_str` is defined the same in both devel and the special branch. I guess I misunderstood how chunking by year works.

So I guess what I thought was happening with that flux datasource with 8000 versions was incorrect. I suppose it's possible that when the data was split into small chunks to upload, the end points of the small chunks overlapped.

**Review by brendan-m-murphy — APPROVED** [review]
Looks good!

**Comment by rt17603** [comment]
> > Yes this isn't in the current devel or master version yet as it's sitting on the parallel [`new_object_store` branch](https://github.com/openghg/openghg/tree/new_object_store) - this is part of the ["Special Release" milestone](https://github.com/openghg/openghg/milestone/13).
> 
> It seems that `get_representative_daterange_str` is defined the same in both devel and the special branch. I guess I misunderstood how chunking by year works.
> 
> So I guess what I thought was happening with that flux datasource with 8000 versions was incorrect. I suppose it's possible that when the data was split into small chunks to upload, the end points of the small chunks overlapped.

In the current code, I believe it's just that every time data is uploaded, if there's already a Datasource present a new version will have been created (even if it's identical to the previous version).

**Comment by rt17603** [comment]
> In the current code, I believe it's just that every time data is uploaded, if there's already a Datasource present a new version will have been created (even if it's identical to the previous version).

Scratch that - that's not quite true.
 - If the file is identical (i.e. same hash) and overwrite=False it won't be re-added
 - If overwrite=True it will always add a new version even if identical
 - If overwrite=False and there's any small change in the new data then a new version will be created

I suspect it's the middle case which may be linked to the 8000 versions.

**Comment by brendan-m-murphy** [comment]
> > In the current code, I believe it's just that every time data is uploaded, if there's already a Datasource present a new version will have been created (even if it's identical to the previous version).
> 
> Scratch that - that's not quite true.
> 
> * If the file is identical (i.e. same hash) and overwrite=False it won't be re-added
> * If overwrite=True it will always add a new version even if identical
> * If overwrite=False and there's any small change in the new data then a new version will be created
> 
> I suspect it's the middle case which may be linked to the 8000 versions.

Maybe, but it looks like 7394 different files were added to the flux with UUID 1349a7aa-fbb8-49c9-859f-65e40d9901e7 (which has the key 'co2_cte-hr-fossil_europe'). So most of the files were new apparently. But this is the last case? So it would create a new version anyway.

**Comment by brendan-m-murphy** [comment]
These are the dates associated with the first 50 files uploaded to that flux datasource (assuming they were added in increasing time order): 

'2021-01-20T02:00:00',
 '2021-04-13T12:00:00',
 '2021-08-15T06:00:00',
 '2021-09-15T03:00:00',
 '2021-02-06T23:00:00',
 '2021-07-11T23:00:00',
 '2021-01-29T14:00:00',
 '2021-06-18T19:00:00',
 '2021-10-12T22:00:00',
 '2021-08-07T04:00:00',
 '2021-05-18T18:00:00',
 '2021-09-11T01:00:00',
 '2021-07-10T18:00:00',
 '2021-04-04T14:00:00',
 '2021-08-03T10:00:00',
 '2021-11-29T12:00:00',
 '2021-08-18T09:00:00',
 '2021-01-10T14:00:00',
 '2021-01-27T15:00:00',
 '2021-09-25T23:00:00',
 '2021-10-06T23:00:00',
 '2021-06-14T19:00:00',
 '2021-04-18T13:00:00',
 '2021-01-03T18:00:00',
 '2021-12-14T13:00:00',
 '2021-10-10T03:00:00',
 '2021-09-07T17:00:00',
 '2021-05-13T08:00:00',
 '2021-02-20T04:00:00',
 '2021-11-28T18:00:00',
 '2021-07-03T22:00:00',
 '2021-10-26T21:00:00',
 '2021-07-05T05:00:00',
 '2021-02-06T08:00:00',
 '2021-02-04T21:00:00',
 '2021-01-30T01:00:00',
 '2021-08-22T02:00:00',
 '2021-11-08T13:00:00',
 '2021-07-16T23:00:00',
 '2021-12-24T15:00:00',
 '2021-05-24T04:00:00',
 '2021-09-11T22:00:00',
 '2021-03-03T17:00:00',
 '2021-01-27T22:00:00',
 '2021-05-30T17:00:00',
 '2021-10-19T16:00:00',
 '2021-11-01T02:00:00',
 '2021-08-31T04:00:00',
 '2021-10-08T14:00:00',
 '2021-05-29T14:00:00'

The files had names like: 'paris_flux_ff_prior_EUROPE_2021-01-20T02:00:00.000000000.nc'

**Review by rt17603 — APPROVED** [review]

**Pull request merged**
