### PR TITLE
Ensure flux/emissions naming is consistent

### LINKED ISSUE #441: Ensure flux/emissions is named consistently
Ensure functions are related to the word "flux" or "emissions" consistently. Favour "flux" where possible as long as documentation includes that this also refers to emissions as well.

### PR DESCRIPTION
**Pull request by rt17603**
* **Summary of changes** (Bug fix, feature, docs update, ...)

Updating naming throughout openghg to use `flux` in preference to `emissions`. This includes the stored object name which will now be `Flux` rather than `Emissions` and the data_type which will now be "flux" rather then "emissions"

* **Please check if the PR fulfills these requirements**

- [x] Closes #441  (Replace xxxx with the Github issue number)
- [x] All code checks passing - `black --line-length 110` run over code, `mypy` and `flake8` not showing any errors
- [x] All tests passing
- [x] Documentation and tutorials updated/added
- [x] Added an entry in the latest `CHANGELOG.md` file if fixing a bug or adding a new feature

### CODE REVIEW

**Comment by gareth-j** [comment]
I get an error when running the tests

```
 tests/retrieve/icos/test_retrieve_icos.py::test_force_allows_storing_twice 
- openghg.types._errors.DataOverlapError: Unable to add new data. Time overlaps with current data
```

**Comment by rt17603** [comment]
> I get an error when running the tests
> 
> ```
>  tests/retrieve/icos/test_retrieve_icos.py::test_force_allows_storing_twice 
> - openghg.types._errors.DataOverlapError: Unable to add new data. Time overlaps with current data
> ```

This should be fixed by PR #828 - mentioned in the PR description, this is unrelated to this PR and came in because of changes made to the way new data is added when existing data is present.

**Comment by rt17603** [comment]
> I get an error when running the tests
> 
> ```
>  tests/retrieve/icos/test_retrieve_icos.py::test_force_allows_storing_twice 
> - openghg.types._errors.DataOverlapError: Unable to add new data. Time overlaps with current data
> ```

Ok, this should now be fixed on this branch.

**Review by gareth-j — APPROVED** [review]
Looks good, all the tests pass for me now.

**Pull request merged**
