### PR TITLE
Adding multiple object store functionality

### PR DESCRIPTION
**Pull request by gareth-j**

### CODE REVIEW

**Comment by rt17603** [comment]
@gareth-j - can this be closed if you now have #647 ?

**Comment by rt17603** [comment]
@gareth-j - just checking again, can this be closed if you now have https://github.com/openghg/openghg/pull/647 ?

**Comment by gareth-j** [comment]
This is now being worked on in #664, I'll check what I need to bring in from this and get it closed.

**Comment by gareth-j** [comment]
Closing this due to working being done on #664

**Pull request closed without merging**
