### PR TITLE
Change to documentation `ipython` directives - Release 0.8.1

### PR DESCRIPTION
**Pull request by SutarPrasad**
This is additional PR that changes the `ipython` directives from the documentation to `code`.
During the release,-0.8.1 the `ipython` directives failed the execution of deploy to docs.

### CODE REVIEW

**Review by gareth-j — APPROVED** [review]
Excellent work everyone!

**Comment by gareth-j** [comment]
Was there another PR into master from devel?

**Comment by rt17603** [comment]
> Was there another PR into master from devel?

Yes - https://github.com/openghg/openghg/pull/1011 is the PR which included the changes listed. It would be worth changing the description of this PR to include just the details which have been changed i.e. the documentation strings and why they needed to be changed.

**Review by rt17603 — COMMENTED** [review]
The changes look fine but the description of this PR should be updated to just include what these changes are and why they have been made.

**Review by rt17603 — APPROVED** [review]

**Pull request merged**
